"""Added investigation fields

Revision ID: 048613aa1af4
Revises: 786c7be027f7
Create Date: 2026-08-18 11:01:09.823719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048613aa1af4'
down_revision = '786c7be027f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='Open', nullable=False))
        batch_op.add_column(sa.Column('investigation_root_cause', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('capa', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deviations', schema=None) as batch_op:
        batch_op.drop_column('closed_at')
        batch_op.drop_column('capa')
        batch_op.drop_column('investigation_root_cause')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
