"""Add training justification

Revision ID: 1bf66a0866e3
Revises: 983fc579c7a0
Create Date: 2026-08-24 21:34:41.315940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf66a0866e3'
down_revision = '983fc579c7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_approval_justification', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.drop_column('manual_approval_justification')

    # ### end Alembic commands ###
