"""Add Change Control tables

Revision ID: 35222b156e6a
Revises: dd9fbc81abf5
Create Date: 2026-08-07 23:31:45.379983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35222b156e6a'
down_revision = 'dd9fbc81abf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('current_state', sa.Text(), nullable=False),
    sa.Column('proposed_state', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('ai_impact_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_control_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['change_control_id'], ['change_controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_tasks')
    op.drop_table('change_controls')
    # ### end Alembic commands ###
