"""Added parsed_content to DocumentVersion

Revision ID: 5ce7d40a3aec
Revises: b0882f7ae984
Create Date: 2026-08-18 15:39:17.884113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce7d40a3aec'
down_revision = 'b0882f7ae984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sop_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('s3_url', sa.String(length=500), nullable=True),
    sa.Column('parsed_content', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_content', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('parsed_content')

    op.drop_table('sop_documents')
    # ### end Alembic commands ###
