"""Added quiz to training record

Revision ID: 686d8e8f38a4
Revises: 1bf66a0866e3
Create Date: 2026-08-25 18:42:26.992029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686d8e8f38a4'
down_revision = '1bf66a0866e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.drop_column('quiz_attempts')
        batch_op.drop_column('quiz_score')

    # ### end Alembic commands ###
