"""Added reviewer_id to DocumentVersion

Revision ID: 753c1285a69a
Revises: ef3229678dfd
Create Date: 2026-08-14 20:04:23.739753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753c1285a69a'
down_revision = 'ef3229678dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewer_id')

    # ### end Alembic commands ###
