"""Added change_reason to DocumentVersion

Revision ID: 983fc579c7a0
Revises: 8781cf991181
Create Date: 2026-08-22 23:08:26.799880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983fc579c7a0'
down_revision = '8781cf991181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_column('change_reason')

    # ### end Alembic commands ###
