"""Added TrainingRecord table

Revision ID: b0882f7ae984
Revises: 048613aa1af4
Create Date: 2026-08-18 13:50:32.827360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0882f7ae984'
down_revision = '048613aa1af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('training_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('document_id', sa.String(length=100), nullable=True),
    sa.Column('classroom_date', sa.String(length=50), nullable=True),
    sa.Column('classroom_time', sa.String(length=50), nullable=True),
    sa.Column('trainer_name', sa.String(length=100), nullable=True),
    sa.Column('ojt_effectiveness', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_records')
    # ### end Alembic commands ###
